<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /var/www/html/wp-content/plugins/enfrte-woo-api-proxy/src/templates/index.latte */
final class Template_024c3c15ec extends Latte\Runtime\Template
{
	public const Source = '/var/www/html/wp-content/plugins/enfrte-woo-api-proxy/src/templates/index.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Hello ';
		echo LR\Filters::escapeHtmlText($name) /* line 1 */;
	}
}
